name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one little script
        run: echo Hello, world!
      
      - name: Run a multiline script
        run: |
          echo Add actions to build
          echo test and deploy project
